image: node:10.14.2-stretch
stages: [deploy]
bundle-stable:
  stage: deploy
  only:
  - julakan-main
  script:
  - npm install gulp-cli
    #- npm install --quiet --no-progress
  - npm install 
  - SOURCEMAPS=true node_modules/.bin/gulp bundle
  artifacts:
    paths:
    - build/ui-bundle.zip
trigger_build:
  stage: deploy
  script:
    #julankan-docs
    #- "curl -X POST -F token=62e9b9b81d2efb0b9ef285be686769 -F ref=main https://gitlab.com/api/v4/projects/19007974/trigger/pipeline"
    #dyu-build
    - "curl -X POST -F token=da164199f9a2c100b4697be7f485ce -F ref=main https://gitlab.com/api/v4/projects/27329450/trigger/pipeline"
    #julakan-build
    - "curl -X POST -F token=7dc04d6e26af2933756aa6fa63a687 -F ref=main https://gitlab.com/api/v4/projects/18171487/trigger/pipeline"
