image: node:10.14.2-stretch
stages: [deploy]
bundle-stable:
  stage: deploy
  only:
  - julakan-main@boydkelly/julakan-docs-ui
  script:
  - npm install --quiet --no-progress
  - node_modules/.bin/gulp bundle
  artifacts:
    paths:
    - build/ui-bundle.zip
trigger_build:
  stage: deploy
  script:
    - "curl -X POST -F token=7dc04d6e26af2933756aa6fa63a687 -F ref=main https://gitlab.com/api/v4/projects/18171487/trigger/pipeline"
