image: node:10.14.2-stretch
stages: [deploy]
bundle-stable:
  stage: deploy
  script:
  - npm install --quiet --no-progress
  - node_modules/.bin/gulp bundle
  artifacts:
    paths:
    - build/ui-bundle.zip
